from typing import Protocol

from app.domain.models.training_run import TrainingRun


class TrainingRunRepository(Protocol):
    def get(self, run_id: str) -> TrainingRun | None: ...
    def create(self, run: TrainingRun) -> bool: ...
    def save(self, run: TrainingRun) -> None: ...
    def list_active(self) -> list[TrainingRun]: ...
    def list_pending_completions(self) -> list[TrainingRun]: ...

