from enum import StrEnum


class TrainingStage(StrEnum):
    STARTING = "STARTING"
    PREPROCESSING = "PREPROCESSING"
    TRAINING = "TRAINING"
    CHECKPOINT_CREATING = "CHECKPOINT_CREATING"
    CHECKPOINT_READY = "CHECKPOINT_READY"
    CANCELED = "CANCELED"
    FAILED = "FAILED"

